"""empty message

Revision ID: 01813711a8dd
Revises: 9edd7643aa0f
Create Date: 2023-07-14 22:13:47.892076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01813711a8dd'
down_revision = '9edd7643aa0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatroom', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatroom', 'title')
    # ### end Alembic commands ###
