"""empty message

Revision ID: 17c53b499a7e
Revises: c662715f4b2e
Create Date: 2023-07-14 22:40:20.685847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c53b499a7e'
down_revision = 'c662715f4b2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
