"""empty message

Revision ID: 19774347bd67
Revises: 100df44f237b
Create Date: 2023-07-15 10:22:23.704846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19774347bd67'
down_revision = '100df44f237b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qna', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'qna', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qna', type_='foreignkey')
    op.drop_column('qna', 'user_id')
    # ### end Alembic commands ###
