"""empty message

Revision ID: 30e384570fa0
Revises: 3872d0c29189
Create Date: 2023-07-18 21:39:37.100037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e384570fa0'
down_revision = '3872d0c29189'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chatroom', ['id'])
    op.create_unique_constraint(None, 'qna', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'qna', type_='unique')
    op.drop_constraint(None, 'chatroom', type_='unique')
    # ### end Alembic commands ###
