"""empty message

Revision ID: 439d7f66acff
Revises: 30e384570fa0
Create Date: 2023-07-18 22:00:04.543199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439d7f66acff'
down_revision = '30e384570fa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
