"""empty message

Revision ID: 499cb6479951
Revises: 01813711a8dd
Create Date: 2023-07-14 22:15:36.410046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499cb6479951'
down_revision = '01813711a8dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qna', sa.Column('chatroom_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'qna', 'chatroom', ['chatroom_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qna', type_='foreignkey')
    op.drop_column('qna', 'chatroom_id')
    # ### end Alembic commands ###
