"""empty message

Revision ID: 9edd7643aa0f
Revises: 59c83982d8e2
Create Date: 2023-07-14 21:52:23.775734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9edd7643aa0f'
down_revision = '59c83982d8e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatroom', 'question')
    op.drop_column('chatroom', 'answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatroom', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('chatroom', sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
