"""empty message

Revision ID: c662715f4b2e
Revises: 499cb6479951
Create Date: 2023-07-14 22:28:26.174199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c662715f4b2e'
down_revision = '499cb6479951'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
